NullPointerException: Cannot invoke ...
"kong.unirest.json.JSONArray.length()" because "subContents" is null
	at de.xmap.jiracloud.JiraCloudAccess$IssueAccess.isPlainText(JiraCloudAccess.java:369)